### ISSUE TITLE
Hiding filenames from exceptions

### ISSUE THREAD

**Issue by ravishaheshan** [sfelix-martins/json-exception-handler#7]
<img width="878" alt="Screen Shot 2019-08-29 at 11 20 37 AM" src="https://user-images.githubusercontent.com/47412190/63914092-c8b45780-ca4f-11e9-9b2b-a3a363d73764.png">

As you can see in the above image, response contains the filename that the error was originated from. When we implement public APIs this is not a good thing. Is there a way to prevent this?

**Comment by sfelix-martins** [comment]
I changed that behavior to return by default an empty string on new tagged version `2.0`
